DROP TABLE IF EXISTS products;

CREATE TABLE products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    price      DOUBLE PRECISION,
    currency   VARCHAR(255),
    url        VARCHAR(1000),
    xpath      VARCHAR(1000),
    price_str  VARCHAR(255),
    last_check BIGINT
);

DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    chat_id  BIGINT PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255)
);

DROP TABLE IF EXISTS subscriptions;

CREATE TABLE subscriptions
(
    chat_id    BIGINT,
    product_id BIGINT,
    FOREIGN KEY(chat_id) REFERENCES users(chat_id) ON DELETE CASCADE,
    FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
    PRIMARY KEY (chat_id, product_id)
);