DROP TABLE IF EXISTS products;

CREATE TABLE products
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    price DOUBLE PRECISION,
    currency VARCHAR(255),
    url    VARCHAR(1000),
    xpath    VARCHAR(1000),
    price_str VARCHAR(255)
);